const products = [
  {
    id: 1,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
  {
    id: 2,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
  {
    id: 3,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
  {
    id: 4,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
  {
    id: 5,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
  {
    id: 6,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
  {
    id: 7,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
  {
    id: 8,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
  {
    id: 9,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
  {
    id: 10,
    title: "ObsidianGlide",
    description: "Introducing the sleek and sophisticated ObsidianGlide, meticulously crafted with a focus on simplicity and balance. Engineered for both style and comfort, this mouse embodies understated elegance with its seamless, matte-black finish that exudes professionalism in any setting.",
    price: 39.99,
    color: "Obsidian",
    image: "mouse.png",
    best_seller: true,
  },
];

module.exports = products;